elasticsearch:
    build: elasticsearch/
    volumes:
        - data:/data
logstash:
    build: logstash/
    ports:
        - "5000:5000"
    links:
        - elasticsearch:elasticsearch
kibana:
    build: kibana/
    ports:
        - "5601:5601"
    links:
        - elasticsearch:elasticsearch